{
  "headers": {
    "x-vio-transactionid": "dbfhjsdb-hfb-do8ryt-876utt7-5ty364ol",
    "clientid": "hsdfgysdhfcdshf37er6twgsdhfjcd",
    "clientsecret": "dsgfhaegur457r6ewsewegrfjesh",
    "content-type": "application/json",
    "accept": "application/json",
    "user-agent": "PostmanRuntime/7.31.3",
    "postman-token": "7f6281fd-09df-4d5c-918a-93b10c821a38",
    "host": "localhost:8083",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "70"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/customers/login",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/customers/login",
  "listenerPath": "/api/*",
  "relativePath": "/api/customers/login",
  "localAddress": "/127.0.0.1:8083",
  "uriParams": {},
  "rawRequestUri": "/api/customers/login",
  "rawRequestPath": "/api/customers/login",
  "remoteAddress": "/127.0.0.1:57372",
  "requestPath": "/api/customers/login"
}