{
  "headers": {
    "x-vio-transactionid": "dbfhjsdb-hfb-do8ryt-876utt7-5ty364ol",
    "clientid": "hsdfgysdhfcdshf37er6twgsdhfjcd",
    "clientsecret": "dsgfhaegur457r6ewsewegrfjesh",
    "content-type": "application/json",
    "accept": "application/json",
    "user-agent": "PostmanRuntime/7.31.3",
    "postman-token": "68fa2453-45b9-4d93-8160-c9baf8e86d67",
    "host": "localhost:8083",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "167"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/notifications",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/notifications",
  "listenerPath": "/api/*",
  "relativePath": "/api/notifications",
  "localAddress": "/127.0.0.1:8083",
  "uriParams": {},
  "rawRequestUri": "/api/notifications",
  "rawRequestPath": "/api/notifications",
  "remoteAddress": "/127.0.0.1:54870",
  "requestPath": "/api/notifications"
}