#%RAML 1.0
title: customer-sapi-raml
description: This RAML file will contain resources for customer process API
baseUri: http://localhost:8081
version: v1

uses:
  common-library: exchange_modules/60bcfbbb-656e-419c-a121-5c3a72bbb760/common-fragment-onboarding/1.0.4/common-fragment-onboarding.raml


/customers:
  /registration:
    post:
      is: [common-library.common-header, common-library.data-header, common-library.common-error]
      body:
        application/json:
          type: common-library.request-registrationPapiSapi
      responses:
        200:
          body:
            application/json:
              type: common-library.response-registration
  /login:
    post:
      is: [common-library.common-header, common-library.data-header, common-library.common-error]
      body:
        application/json:
          type: !include dataType/login-request-dataType.raml
      responses:
        200:
          body:
            application/json:
              type: common-library.response-registration

/notifications:
  post:
    is: [common-library.common-header, common-library.data-header, common-library.common-error]
    body:
      application/json:
        type: !include dataType/notification-dataType.raml
    responses:
      200:
        body:
          application/json:
            type: common-library.response-registration
